"""Conformance vectors: (graph, proven state) -> expected ``sees()`` / verdicts, generated by the
reference solver's CI. Any other traversal (the visualizer's TypeScript one) replays them
verbatim — one specification, two runtimes, one golden suite. Divergence is a red CI, never a
wrong drawing in the dome.
"""

from pydantic import BaseModel, ConfigDict, Field

from datamodels.optics.graph import OpticalComponentSpec
from datamodels.optics.results import CheckResult, SeesRecord
from datamodels.optics.vocabulary import ComponentName, Symbol

SCHEMA_VERSION = 1


class SelectorState(BaseModel):
    """Proven state of one selector as the solver sees it. ``position=None`` means the readback
    maps to no declared symbol (the oca-problems#107 case: M3 reports "2"); together with
    ``moving`` and ``stale`` that is exactly what makes a path ``undefined``."""

    model_config = ConfigDict(extra="forbid")

    position: Symbol | None = None
    moving: bool = False
    stale: bool = False
    raw: str | int | float | None = None  #: the hardware readback, for the record


class Environment(BaseModel):
    """Inputs to derived selectors and stateful sources. Open — a new predicate adds a field."""

    model_config = ConfigDict(extra="allow")

    sun_alt_deg: float | None = None
    dome_az_deg: float | None = None
    mount_az_deg: float | None = None
    mount_alt_deg: float | None = None


class ConformanceVector(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str
    description: str | None = None
    components: dict[ComponentName, OpticalComponentSpec]
    state: dict[ComponentName, SelectorState] = Field(default_factory=dict)
    environment: Environment = Field(default_factory=Environment)
    expected_sees: dict[ComponentName, list[SeesRecord]]  #: per detector; order-insensitive (a set)
    expected_checks: list[CheckResult] = Field(default_factory=list)


class ConformanceSuite(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: int = SCHEMA_VERSION
    generated_from: str  #: solver version / commit that produced the vectors
    vectors: list[ConformanceVector]
