"""Conformance vectors: (graph, proven state, environment) -> expected ``sees()`` / verdicts,
generated by the reference solver's CI. Any other traversal (the visualizer's TypeScript one) replays them
verbatim — one specification, two runtimes, one golden suite. Divergence is a red CI, never a
wrong drawing in the dome.
"""

from typing import Annotated, Literal

from pydantic import AfterValidator, BaseModel, ConfigDict, Field

from datamodels.optics.graph import OpticalComponentSpec
from datamodels.optics.results import CheckResult, SeesRecord
from datamodels.optics.vocabulary import CLOSED_NAME_KEYS, CLOSED_STATE_KEYS, ComponentName, JsonInteger, JsonNumber, StateKey, Symbol

SCHEMA_VERSION = 1


class SelectorState(BaseModel):
    """Proven state of one selector as the solver sees it. ``position=None`` means the readback
    maps to no declared symbol (the oca-problems#107 case: M3 reports "2"); together with
    ``moving`` and ``stale`` that is exactly what makes a path ``undefined``."""

    model_config = ConfigDict(extra="forbid")

    position: Symbol | None = None
    moving: bool = False
    stale: bool = False
    raw: bool | str | JsonInteger | JsonNumber | None = None  #: the hardware readback as reported (a Boolean stays a Boolean), for the record


class Environment(BaseModel):
    """Inputs to derived selectors and stateful sources. Open — a new predicate adds a field."""

    model_config = ConfigDict(extra="allow")

    sun_alt_deg: JsonNumber | None = None
    dome_shutter_open: bool | None = None
    dome_az_deg: JsonNumber | None = None
    mount_az_deg: JsonNumber | None = None
    mount_alt_deg: JsonNumber | None = None


def _canonical(records: list[SeesRecord]) -> list[SeesRecord]:
    """Reject duplicates and store the set in one canonical order (by class, terminal, via), so
    that equal sets compare and serialize equal whatever order the generator emitted them in."""
    if len(set(records)) != len(records):
        raise ValueError("expected_sees is a set: duplicate records")
    return sorted(records, key=lambda r: (r.light_class, r.terminal, r.via))


#: ``sees()`` is a set: no duplicates (``uniqueItems`` in the schema), canonical order in Python. A
#: replay client compares this field as a set — JSON Schema cannot express order-insensitivity.
SeesSet = Annotated[list[SeesRecord], AfterValidator(_canonical), Field(json_schema_extra={"uniqueItems": True})]


class ConformanceVector(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str
    description: str | None = None
    components: dict[ComponentName, OpticalComponentSpec] = Field(json_schema_extra=CLOSED_NAME_KEYS)
    state: dict[StateKey, SelectorState] = Field(default_factory=dict, json_schema_extra=CLOSED_STATE_KEYS)  #: keyed by selector, or ``selector.aspect``
    environment: Environment = Field(default_factory=Environment)
    expected_sees: dict[ComponentName, SeesSet] = Field(json_schema_extra=CLOSED_NAME_KEYS)  #: per detector
    expected_checks: list[CheckResult] = Field(default_factory=list)


class ConformanceSuite(BaseModel):
    model_config = ConfigDict(extra="forbid")

    schema_version: Literal[1] = SCHEMA_VERSION
    generated_from: str  #: solver version / commit that produced the vectors
    vectors: list[ConformanceVector]
