"""JSON Schema export — the contract TypeScript clients generate their types from.

Run ``datamodels-export-schemas [out_dir]`` (default ``schemas/optics``). The committed files
are checked against a fresh export in the tests, so schema drift fails CI.

The generator is pinned, the library is not: pydantic's schema output changes between releases
(key order, where ``title`` lands, how bounds render), so a byte-for-byte drift check is only
reproducible under one known version. :data:`GENERATOR_PYDANTIC` is that version; every schema
records it in ``$comment``, the exporter refuses to run under any other, and the drift test skips
instead of failing under another. Bumping the generator is a deliberate commit: change the pin,
regenerate, and the diff shows exactly what pydantic changed.
"""

import json
import sys
from enum import Enum
from pathlib import Path
from typing import Any

import pydantic
from pydantic import BaseModel, TypeAdapter

import datamodels.optics as optics
from datamodels.optics.results import Verdict

DEFAULT_OUT_DIR = Path("schemas") / "optics"

#: The one pydantic version the committed schemas are generated with. Regenerate with
#: ``uv run --with pydantic==<this> datamodels-export-schemas`` (CI does exactly that).
GENERATOR_PYDANTIC = "2.13.4"


class GeneratorMismatch(RuntimeError):
    """The exporter runs under a pydantic other than :data:`GENERATOR_PYDANTIC`."""


def generator_matches() -> bool:
    return pydantic.VERSION == GENERATOR_PYDANTIC


def _public_contracts() -> dict[str, Any]:
    """Every public model and enum of ``datamodels.optics`` (from its ``__all__``), plus the
    ``Verdict`` union — one schema file each, so the registry cannot drift from the package API.
    Identifier aliases (``ComponentName`` …) are not contracts of their own; they appear inline."""
    exported: dict[str, Any] = {}
    for name in optics.__all__:
        obj = getattr(optics, name)
        if isinstance(obj, type) and (issubclass(obj, BaseModel) or issubclass(obj, Enum)):
            exported[name] = obj
    exported["Verdict"] = Verdict
    return dict(sorted(exported.items()))


#: name -> type; one schema file per entry
EXPORTED: dict[str, Any] = _public_contracts()


def json_schemas() -> dict[str, dict[str, Any]]:
    """Every exported schema, keyed by name, with a stable ``$id``."""
    comment = f"generated by pydantic {GENERATOR_PYDANTIC}; regenerate with the same version (datamodels-export-schemas)"
    return {
        name: {
            "$id": f"https://araucaria-project.github.io/datamodels/optics/{name}.schema.json",
            "$comment": comment,
            **TypeAdapter(tp).json_schema(),
        }
        for name, tp in EXPORTED.items()
    }


def render(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def export_json_schemas(out_dir: Path = DEFAULT_OUT_DIR) -> dict[str, Path]:
    if not generator_matches():
        raise GeneratorMismatch(
            f"schemas are generated with pydantic {GENERATOR_PYDANTIC}, this environment has {pydantic.VERSION}; "
            f"run `uv run --with pydantic=={GENERATOR_PYDANTIC} datamodels-export-schemas` or bump GENERATOR_PYDANTIC deliberately"
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for name, schema in json_schemas().items():
        path = out_dir / f"{name}.schema.json"
        path.write_text(render(schema), encoding="utf-8")
        written[name] = path
    return written


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    out_dir = Path(args[0]) if args else DEFAULT_OUT_DIR
    try:
        written = export_json_schemas(out_dir)
    except GeneratorMismatch as e:
        print(e, file=sys.stderr)
        return 2
    for name, path in written.items():
        print(f"{name:24s} -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
