"""JSON Schema export — the contract TypeScript clients generate their types from.

The pydantic models are the only source of truth; a schema is a **build artifact**, like a wheel:
never committed, generated by the release workflow under one pinned pydantic and published with the
version it belongs to (GitHub Release asset ``optics-schemas-v<version>.zip``, ``$id`` carries the
version). Nothing in the repository is diffed against generator output, so a pydantic release
cannot make CI red with unchanged sources.

``datamodels-export-schemas [out_dir]`` (default ``schemas/optics``, gitignored) is what the
release job runs and what a developer runs to look at the output. :data:`GENERATOR_PYDANTIC` is the
toolchain pin: the exporter refuses any other version, every file records it in ``$comment``.
Bumping it is an ordinary toolchain change.
"""

import json
import sys
from enum import Enum
from importlib.metadata import PackageNotFoundError, version
from pathlib import Path
from typing import Any

import pydantic
from pydantic import BaseModel, TypeAdapter

import datamodels.optics as optics
from datamodels.optics.results import Verdict

DEFAULT_OUT_DIR = Path("schemas") / "optics"

#: The one pydantic version schemas are generated with. Run the exporter as
#: ``uv run --with pydantic==<this> datamodels-export-schemas`` (the release job does exactly that).
GENERATOR_PYDANTIC = "2.13.4"


def package_version() -> str:
    try:
        return version("datamodels")
    except PackageNotFoundError:
        return "0.0.0"


class GeneratorMismatch(RuntimeError):
    """The exporter runs under a pydantic other than :data:`GENERATOR_PYDANTIC`."""


def generator_matches() -> bool:
    return pydantic.VERSION == GENERATOR_PYDANTIC


def _public_contracts() -> dict[str, Any]:
    """Every public model and enum of ``datamodels.optics`` (from its ``__all__``), plus the
    ``Verdict`` union — one schema file each, so the registry cannot drift from the package API.
    Identifier aliases (``ComponentName`` …) are not contracts of their own; they appear inline."""
    exported: dict[str, Any] = {}
    for name in optics.__all__:
        obj = getattr(optics, name)
        if isinstance(obj, type) and (issubclass(obj, BaseModel) or issubclass(obj, Enum)):
            exported[name] = obj
    exported["Verdict"] = Verdict
    return dict(sorted(exported.items()))


#: name -> type; one schema file per entry
EXPORTED: dict[str, Any] = _public_contracts()


def json_schemas() -> dict[str, dict[str, Any]]:
    """Every exported schema, keyed by name; ``$id`` names the datamodels version it belongs to."""
    release = package_version()
    comment = f"datamodels {release}, generated by pydantic {GENERATOR_PYDANTIC}; a build artifact — regenerate, never edit"
    return {
        name: {
            "$id": f"https://araucaria-project.github.io/datamodels/optics/{release}/{name}.schema.json",
            "$comment": comment,
            **TypeAdapter(tp).json_schema(),
        }
        for name, tp in EXPORTED.items()
    }


def render(schema: dict[str, Any]) -> str:
    return json.dumps(schema, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def export_json_schemas(out_dir: Path = DEFAULT_OUT_DIR) -> dict[str, Path]:
    if not generator_matches():
        raise GeneratorMismatch(
            f"schemas are generated with pydantic {GENERATOR_PYDANTIC}, this environment has {pydantic.VERSION}; "
            f"run `uv run --with pydantic=={GENERATOR_PYDANTIC} datamodels-export-schemas` or bump GENERATOR_PYDANTIC deliberately"
        )
    out_dir.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}
    for name, schema in json_schemas().items():
        path = out_dir / f"{name}.schema.json"
        path.write_text(render(schema), encoding="utf-8")
        written[name] = path
    for stale in out_dir.glob("*.schema.json"):
        if stale not in written.values():
            stale.unlink()  # a renamed or removed contract must not linger as a schema nobody exports
    return written


def main(argv: list[str] | None = None) -> int:
    args = sys.argv[1:] if argv is None else argv
    out_dir = Path(args[0]) if args else DEFAULT_OUT_DIR
    try:
        written = export_json_schemas(out_dir)
    except GeneratorMismatch as e:
        print(e, file=sys.stderr)
        return 2
    for name, path in written.items():
        print(f"{name:24s} -> {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
